/*
 * Decompiled with CFR 0.152.
 */
package com.github.catvod.spider.merge.H1;

import com.github.catvod.spider.merge.B.e;
import com.github.catvod.spider.merge.H1.p;
import com.github.catvod.spider.merge.k1.i;

public final class o {
    private String a;
    private String b;
    private boolean c;
    private i d;
    private String e;
    private Boolean f;

    public final p a() {
        if (this.b != null) {
            String string = this.e;
            if (string != null) {
                if (this.f != null) {
                    if (this.a == null) {
                        Object object = this.d;
                        object = object != null ? com.github.catvod.spider.merge.B.e.c(".", object.b) : "";
                        this.a = com.github.catvod.spider.merge.B.e.c(string, (String)object);
                    }
                    return new p(this.a, this.b, this.c, this.d, this.e, this.f);
                }
                throw new IllegalStateException("The subtitles stream has been not set as an autogenerated subtitles stream or not. Please specify this information with setIsAutoGenerated.");
            }
            throw new IllegalStateException("The language code of the subtitles stream has been not set or is null. Make sure you specified an non null language code with setLanguageCode.");
        }
        throw new IllegalStateException("No valid content was specified. Please specify a valid one with setContent.");
    }

    public final o b(boolean bl) {
        this.f = bl;
        return this;
    }

    public final o c(String string) {
        this.b = string;
        this.c = true;
        return this;
    }

    public final o d(String string) {
        this.e = string;
        return this;
    }

    public final o e(i i2) {
        this.d = i2;
        return this;
    }
}

